### ISSUE TITLE
Update the rdmo-app to use split settings and environment variables.

### ISSUE THREAD

**Issue by MyPyDavid** [rdmorganiser/rdmo-app#11]
I've changed the rdmo-app to use environment variables (via [python-dotenv](https://github.com/theskumar/python-dotenv)) and split settings (eg. `debug.py` and `production.py`) in here:
* https://github.com/ULB-Darmstadt/rdmo-app/tree/main/config/settings

Would it be useful to make this the standard for the rdmo-app `master` branch? 
Might be hard to say with all the different deployments of rdmo out there..

The split settings implementation could also be modified, to use a `.py` for each authentication method for example. (`allauth.py`, `shibboleth.py`, `ldap.py` etc..)

**Comment by jochenklar** [comment]
Hi @MyPyDavid I use a similiar configuration here: https://github.com/jochenklar/rdmo.jochenklar.dev/blob/master/config/settings/local.py and in the new instances I set up.

One thing: I would not do the env file loading in the settings file, since for e.g. gunicorn or docker you set the variables using different processes and only need django-dotenv in development, e.g. https://github.com/jochenklar/rdmo.jochenklar.dev/blob/master/etc/systemd/system/rdmo.service#L10.

I also usually keep the file `local.py` so that the documentation still makes sense, but include it in the repo.

Nevertheless I think we should change the rdmo-app to use env variables at one point in the not to distant future.

**Comment by afuetterer** [comment]
This was addressed in #12, right? Do you want discuss this any further?

**Comment by jochenklar** [comment]
Yes, lets close here. I have my setup now at https://github.com/jochenklar/rdmo-app/tree/development.
